**Expectation Maximaztion Algorithm**

Create 2 synthetic normal distribution N(0,1), N(-1,3)

In [1]:
import numpy as np
from scipy.stats import norm

s1 = np.random.normal(0, 1, 10000) # weight = 2/3
s2 = np.random.normal(-1, 3, 5000) # weight = 1/3
data = np.r_[s1,s2]

**Main**

In [2]:
# initialize 
# wild guess
w  = [0.5,0.5]
mu = [10,-10]
sig= [10,10]

loglk_list = []
iter_n = 0

# start EM algo
while True:
    w = np.array(w)
    p = np.array([norm.pdf(data,m,s) for m, s in zip(mu,sig)]) # = P(data|dist_i)

    mod_w = w[:,np.newaxis]*p            # [:, newaxis] > from 1 d to 2 d array
    mod_w = mod_w / np.sum(mod_w,axis=0) # = P(data belongs to dist_i | data)
    mod_p = mod_w * p                    # * is element-wise, @ is matrix multiplication
    loglk = np.sum(np.log(mod_p))        # log-likelihood to be maximize

    # update parameters
    w   = np.mean(mod_w,axis=1)                                                         # new weight
    mu  = np.sum(mod_w*data, axis=1)/np.sum(mod_w,axis=1)                               # weighted mean
    sig = (np.sum(mod_w*(data-mu[:,np.newaxis])**2,axis=1) / np.sum(mod_w,axis=1))**0.5 # weighted std

    if len(loglk_list)>0 and abs(loglk / loglk_list[-1] - 1) < 0.0000001:
        break

    if iter_n > 1000:
        break

    loglk_list.append(loglk)
    iter_n += 1
    
    print('Iteration: ' ,iter_n, ' with log-likelihood: ',loglk)

Iteration:  1  with log-likelihood:  -133621.09940034308
Iteration:  2  with log-likelihood:  -85425.29363326226
Iteration:  3  with log-likelihood:  -87913.38733762111
Iteration:  4  with log-likelihood:  -94219.35743935725
Iteration:  5  with log-likelihood:  -103529.11392701081
Iteration:  6  with log-likelihood:  -111998.02597265708
Iteration:  7  with log-likelihood:  -117474.80832035965
Iteration:  8  with log-likelihood:  -120268.28554506549
Iteration:  9  with log-likelihood:  -121407.36725584202
Iteration:  10  with log-likelihood:  -121699.04924258568
Iteration:  11  with log-likelihood:  -121605.82320637853
Iteration:  12  with log-likelihood:  -121358.85848656115
Iteration:  13  with log-likelihood:  -121065.27946765377
Iteration:  14  with log-likelihood:  -120771.76861591838
Iteration:  15  with log-likelihood:  -120496.98932988752
Iteration:  16  with log-likelihood:  -120247.06560396226
Iteration:  17  with log-likelihood:  -120022.72830942592
Iteration:  18  with log-l

In [3]:
mu

array([ 0.00221388, -0.96698346])

In [4]:
sig

array([1.00148815, 2.99413772])

In [5]:
w

array([0.66191984, 0.33808016])

What we have got is pretty close to the synthetic data.